[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"

[project]
name = "campusflow"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.5",
    "fastapi[mail]>=0.141.1",
    "fastapi-sso>=0.21.1",
    "httpx>=0.28.1",
    "passlib[bccrypt,bcrypt,bgcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pydantic[email]>=2.13.4",
    "python-dotenv>=1.2.2",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
    "fastapi-mail>=1.6.5",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "aiosqlite>=0.22.1",
]
